### ISSUE TITLE
主页的那个表格数据统计问题？

### ISSUE THREAD

**Issue by MQ-0707** [yihong0618/2022#18]
Yihong老师，你好。请问一下主页的表格统计数字，如果我只想要早起和俯卧撑锻炼这两项，我做个统计的时候，只要修改main和getup这两个py 文件就可以吗？还有建立两个issue和对应的actions 就可以了吗？![image](https://user-images.githubusercontent.com/74593661/225195130-1f5a16de-3175-48c9-8d08-8a4da9b456d4.jpeg)

**Comment by yihong0618** [comment]
有个 config dict 往里填才有

**Comment by MQ-0707** [comment]
> 有个 config dict 往里填才有

Yihong老师，打扰了，我只想统计早起和俯卧撑锻炼的记录表格，不需要别的记录，只需要fork你的那几个文件就可以定时刷新生成这个表格md文件，可以给个图片截图，那几个文件，我自己研究吗？谢谢🙏。

**Comment by yihong0618** [comment]
@MQ-0707 

改这个，但你要彻底能用还有很长的路要走。。。
这个太个人定制向了，除非你能看懂代码，知道 Actions 怎么走。
https://github.com/yihong0618/2022/blob/ae068f33779d43ebfd21cb9b8b3d5338c171a7a0/daily/__init__.py#L13-L19
